# Generated by Django 4.1 on 2022-10-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_name_photos_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='strengths',
            field=models.TextField(),
        ),
    ]
