# Generated by Django 4.1 on 2022-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Strengths', models.CharField(max_length=200)),
                ('Weaknesses', models.TextField()),
            ],
        ),
    ]
