# Generated by Django 4.1 on 2022-10-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='Strengths',
            new_name='strengths',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='Weaknesses',
            new_name='weaknesses',
        ),
    ]
