# Generated by Django 4.1 on 2022-10-13 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photos_strengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Photos'),
            preserve_default=False,
        ),
    ]
