# Generated by Django 4.1 on 2022-10-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_hero_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(default='description', max_length=2000),
        ),
        migrations.AddField(
            model_name='hero',
            name='identity',
            field=models.TextField(default='identity', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='strengths', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strengths',
            field=models.TextField(default='strengths', max_length=500),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weaknesses',
            field=models.TextField(default='weaknesses', max_length=500),
        ),
    ]
