# Generated by Django 4.1.2 on 2022-10-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_hero_description_hero_identity_alter_hero_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
