# Generated by Django 4.1.3 on 2022-11-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
