# Generated by Django 4.1.3 on 2022-11-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_hero_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('hero', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='photos.author')),
            ],
        ),
    ]
