# Generated by Django 4.1.3 on 2022-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='hero',
            name='notes',
            field=models.TextField(default='notes', max_length=2000),
        ),
    ]
